### ISSUE TITLE
FIle Uploading Problem - Exception 500

### ISSUE THREAD

**Issue by sergey-nechaev** [Element-34/php-webdriver#37]
My code thows the exception 500.

```
    self::$session->open('http://localhost/test/file/1.php');
    $file1 = dirname(__FILE__) . '/files/1.jpg';
    $e = self::$session->element('name', 'fUserPhoto');
    $e->sendKeys($file1);
```

I tried the FileUploadTest.php, it's not working, same reason. Any ideas?

Here is the selenium output:

19:18:34.347 INFO - Executing: [get: http://localhost/test/file/1.php] at URL: /session/3341c498-6135-4129-bbe0-a4c00aab4c3e/url)
19:18:35.093 INFO - Done: /session/3341c498-6135-4129-bbe0-a4c00aab4c3e/url
19:18:35.104 INFO - Executing: [find element: By.name: fUserPhoto] at URL: /session/3341c498-6135-4129-bbe0-a4c00aab4c3e/element)
19:18:35.150 INFO - Done: /session/3341c498-6135-4129-bbe0-a4c00aab4c3e/element
19:18:35.169 INFO - Executing: org.openqa.selenium.remote.server.handler.UploadFile@a9e1af at URL: /session/3341c498-6135-4129-bbe0-a4c00aab4c3e/file)
19:18:35.175 INFO - Done: /session/3341c498-6135-4129-bbe0-a4c00aab4c3e/file
19:18:35.186 WARN - Fatal, unhandled exception: /session/3341c498-6135-4129-bbe0-a4c00aab4c3e/element/0/value: java.lang.NumberFormatException: For input string: "ploa"
19:18:35.187 INFO - WebDriver remote server: Fatal, unhandled exception: /session/3341c498-6135-4129-bbe0-a4c00aab4c3e/element/0/value: org.openqa.selenium.WebDriverException: java.lang.NumberFormatException: For input string: "ploa"
Build info: version: '2.31.0', revision: '1bd294d', time: '2013-02-27 20:52:59'
System info: os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_17'
Driver info: driver.version: unknown
19:18:35.187 WARN - EXCEPTION
javax.servlet.ServletException: org.openqa.selenium.WebDriverException: java.lan
g.NumberFormatException: For input string: "ploa"
Build info: version: '2.31.0', revision: '1bd294d', time: '2013-02-27 20:52:59'
System info: os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.versi
on: '1.7.0_17'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverS
ervlet.java:206)
        at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.
java:167)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet
.java:139)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.jav
a:428)
        at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler
.java:677)
        at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.j
ava:568)
        at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
        at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
        at org.openqa.jetty.http.HttpServer.service(HttpServer.java:914)
        at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)

```
    at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:9
```

86)
        at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
        at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.
java:243)
        at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:357)
        at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:534)
Caused by: org.openqa.selenium.WebDriverException: java.lang.NumberFormatExcepti
on: For input string: "ploa"
Build info: version: '2.31.0', revision: '1bd294d', time: '2013-02-27 20:52:59'
System info: os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.versi
on: '1.7.0_17'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.server.JsonHttpRemoteConfig.handleRequest(
JsonHttpRemoteConfig.java:199)
        at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverS
ervlet.java:201)
        ... 16 more
Caused by: java.lang.NumberFormatException: For input string: "ploa"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at org.json.JSONTokener.nextString(JSONTokener.java:294)
        at org.json.JSONTokener.nextValue(JSONTokener.java:371)
        at org.json.JSONArray.<init>(JSONArray.java:127)
        at org.json.JSONTokener.nextValue(JSONTokener.java:378)
        at org.json.JSONObject.<init>(JSONObject.java:206)
        at org.json.JSONObject.<init>(JSONObject.java:403)
        at org.openqa.selenium.remote.JsonToBeanConverter.convert(JsonToBeanConv
erter.java:202)
        at org.openqa.selenium.remote.JsonToBeanConverter.convert(JsonToBeanConv
erter.java:42)
        at org.openqa.selenium.remote.server.rest.ResultConfig.setJsonParameters
(ResultConfig.java:299)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConf
ig.java:191)
        at org.openqa.selenium.remote.server.JsonHttpRemoteConfig.handleRequest(
JsonHttpRemoteConfig.java:192)
        ... 17 more
19:18:35.190 ERROR - /wd/hub/session/3341c498-6135-4129-bbe0-a4c00aab4c3e/elemen
t/0/value:
org.openqa.selenium.WebDriverException: java.lang.NumberFormatException: For inp
ut string: "ploa"
Build info: version: '2.31.0', revision: '1bd294d', time: '2013-02-27 20:52:59'
System info: os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.versi
on: '1.7.0_17'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.server.JsonHttpRemoteConfig.handleRequest(
JsonHttpRemoteConfig.java:199)
        at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverS
ervlet.java:201)
        at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.
java:167)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet
.java:139)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.jav
a:428)
        at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler
.java:677)
        at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.j
ava:568)
        at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
        at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
        at org.openqa.jetty.http.HttpServer.service(HttpServer.java:914)
        at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)

```
    at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:9
```

86)
        at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
        at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.
java:243)
        at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:357)
        at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:534)
Caused by: java.lang.NumberFormatException: For input string: "ploa"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at org.json.JSONTokener.nextString(JSONTokener.java:294)
        at org.json.JSONTokener.nextValue(JSONTokener.java:371)
        at org.json.JSONArray.<init>(JSONArray.java:127)
        at org.json.JSONTokener.nextValue(JSONTokener.java:378)
        at org.json.JSONObject.<init>(JSONObject.java:206)
        at org.json.JSONObject.<init>(JSONObject.java:403)
        at org.openqa.selenium.remote.JsonToBeanConverter.convert(JsonToBeanConv
erter.java:202)
        at org.openqa.selenium.remote.JsonToBeanConverter.convert(JsonToBeanConv
erter.java:42)
        at org.openqa.selenium.remote.server.rest.ResultConfig.setJsonParameters
(ResultConfig.java:299)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConf
ig.java:191)
        at org.openqa.selenium.remote.server.JsonHttpRemoteConfig.handleRequest(
JsonHttpRemoteConfig.java:192)
        ... 17 more

**Comment by adamgoucher** [comment]
Alright. Got it reproduced in my XP VM. Now for figure out the why. And the fix.

**Comment by adamgoucher** [comment]
Fixed in https://github.com/Element-34/php-webdriver/commit/31418ce23b1a87f263fac8bf775bfde63d6383e6#PHPWebDriver/WebDriverBase.php. Will package up and release properly tomorrow.
